buggy0:
  name: "Buggy0"
  sonar0:
    angle: 0
    position: [0, 9]
    number: 0
  sonar1:
    angle: 90
    position: [6, 7]
    number: 1
  sonar2:
    angle: 270
    position: [-6, 7]
    number: 2
  encoder0:
    number: 0
  encoder1:
    number: 1
  servo0:
    number: 0
    orientation: yaw
