buggy0:
  name: "Buggy0"
  number: 0
  sonar0:
    angle: 0
    position: [0, 9]
    number: 0
  sonar1:
    angle: 45
    position: [6, 7]
    number: 1
  sonar2:
    angle: 315
    position: [-6, 7]
    number: 2
  sonar3:
    angle: 90
    position: [6, -1]
    number: 3
  sonar4:
    angle: 270
    position: [-6, -4]
    number: 4
  encoder0:
    number: 0
  encoder1:
    number: 1
  servo0:
    number: 0
    orientation: 1
    pin: 27
  camera0:
    number: 0
    position: [0, 9]
    pitch: 0
    yaw: 0

