buggy0:
  name: "Buggy0"
  number: 0
  sonar0:
    angle: 0
    position: [0, 9]
    number: 0
    min_dist: 20
    action: "Reverse"
  sonar1:
    angle: 20
    position: [-6, 7]
    number: 1
    min_dist: 20
    action: "Right"
  sonar2:
    angle: 330
    position: [6, 7]
    number: 2
    min_dist: 20
    action: "Left"
  sonar3:
    angle: 270
    position: [6, -1]
    number: 3
    min_dist: 10
    action: "None"
  sonar4:
    angle: 90
    position: [-6, -4]
    number: 4
    min_dist: 10
    action: "None"
  encoder0:
    number: 0
    dist_per_tick: 0.5
  encoder1:
    number: 1
    dist_per_tick: 0.5
  servo0:
    number: 0
    axis: 0
    max: 90
    min: -90
  servo1:
    number: 1
    axis: 1
    max: 90
    min: -25
  camera0:
    number: 0
    position: [0, 9]
    pitch: 0
    yaw: 0
  gyroscope:
    number: 0
    axis: 0

