// Generated by gencpp from file multi_tier_robot_system/Drive.msg
// DO NOT EDIT!


#ifndef MULTI_TIER_ROBOT_SYSTEM_MESSAGE_DRIVE_H
#define MULTI_TIER_ROBOT_SYSTEM_MESSAGE_DRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_tier_robot_system
{
template <class ContainerAllocator>
struct Drive_
{
  typedef Drive_<ContainerAllocator> Type;

  Drive_()
    : left(0)
    , right(0)
    , left_dir(false)
    , right_dir(false)  {
    }
  Drive_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)
    , left_dir(false)
    , right_dir(false)  {
  (void)_alloc;
    }



   typedef uint8_t _left_type;
  _left_type left;

   typedef uint8_t _right_type;
  _right_type right;

   typedef uint8_t _left_dir_type;
  _left_dir_type left_dir;

   typedef uint8_t _right_dir_type;
  _right_dir_type right_dir;




  typedef boost::shared_ptr< ::multi_tier_robot_system::Drive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_tier_robot_system::Drive_<ContainerAllocator> const> ConstPtr;

}; // struct Drive_

typedef ::multi_tier_robot_system::Drive_<std::allocator<void> > Drive;

typedef boost::shared_ptr< ::multi_tier_robot_system::Drive > DrivePtr;
typedef boost::shared_ptr< ::multi_tier_robot_system::Drive const> DriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_tier_robot_system::Drive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_tier_robot_system::Drive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multi_tier_robot_system

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'multi_tier_robot_system': ['/home/samuel/Documents/Multi-tier-Robot-System/ROS/src/multi_tier_robot_system/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multi_tier_robot_system::Drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_tier_robot_system::Drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_tier_robot_system::Drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_tier_robot_system::Drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_tier_robot_system::Drive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_tier_robot_system::Drive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_tier_robot_system::Drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc315fdef9b03fd8f24388694d69978e";
  }

  static const char* value(const ::multi_tier_robot_system::Drive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc315fdef9b03fd8ULL;
  static const uint64_t static_value2 = 0xf24388694d69978eULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_tier_robot_system::Drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_tier_robot_system/Drive";
  }

  static const char* value(const ::multi_tier_robot_system::Drive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_tier_robot_system::Drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 left\n\
uint8 right\n\
bool left_dir\n\
bool right_dir\n\
";
  }

  static const char* value(const ::multi_tier_robot_system::Drive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_tier_robot_system::Drive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.left_dir);
      stream.next(m.right_dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Drive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_tier_robot_system::Drive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_tier_robot_system::Drive_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right);
    s << indent << "left_dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_dir);
    s << indent << "right_dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_TIER_ROBOT_SYSTEM_MESSAGE_DRIVE_H
